env:
    browser: true
    es2021: true
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - '@typescript-eslint'
rules: 
    no-console: warn
    prefer-const: warn
    indent: 
        - warn
        - 4
    max-len:
        - warn
        - code: 200
    quotes: 
        - warn 
        - single
    comma-dangle:
        - warn
        - never
